stages:
  combine_data:
    cmd: python src/combine_data.py --config=params.yaml
    deps:
      - src/combine_data.py
    outs:
      - data/combined/combined_AReM_data.csv

  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/load_data.py
      - src/get_data.py
      - data/combined/combined_AReM_data.csv
    outs:
      - data/raw/combined_AReM_data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - data/raw/combined_AReM_data.csv
    outs:
      - data/processed/train_AReM_data.csv
      - data/processed/test_AReM_data.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - src/train_and_evaluate.py
      - data/processed/train_AReM_data.csv
      - data/processed/test_AReM_data.csv
    params:
      - algorithm_params.solver
    metrics:
      - report/scores.json:
          cache: false
      - report/params.json:
          cache: false
    outs:
      - saved_models/model.joblib
